version: '3.3'  # version of compose format

services:
  addition:
    build: ./landing/app/addition
    ports: 
      - 5046:5046
    networks:
       sample:
          aliases:
            - addition 
  multiplication:
    build: ./landing/app/multiplication
    ports: 
      - 5047:5047
    networks:
       sample:
          aliases:
            - multiplication 
  subtraction:
    build: ./landing/app/subtraction
    ports: 
      - 5048:5048
    networks:
       sample:
          aliases:
            - subtraction 
  division:
    build: ./landing/app/division
    ports: 
      - 5049:5049
    networks:
       sample:
          aliases:
            - division 
  equalto:
    build: ./landing/app/EqualTo
    ports: 
      - 5051:5051
    networks:
       sample:
          aliases:
            - equalto
  exponent:
    build: ./landing/app/Exponent
    ports: 
      - 5052:5052
    networks:
       sample:
          aliases:
            - exponent
  gcd:
    build: ./landing/app/GCD
    ports: 
      - 5053:5053
    networks:
       sample:
          aliases:
            - gcd
  greaterthan:
    build: ./landing/app/GreaterThan
    ports: 
      - 5054:5054
    networks:
       sample:
          aliases:
            - greatthan
  lcm:
    build: ./landing/app/LCM
    ports: 
      - 5055:5055
    networks:
       sample:
          aliases:
            - lcm
  lessthan:
    build: ./landing/app/LessThan
    ports: 
      - 5056:5056
    networks:
       sample:
          aliases:
            - lessthan
  modulus:
    build: ./landing/app/Modulus
    ports: 
      - 5057:5057
    networks:
       sample:
          aliases:
            - modulus
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    depends_on:
      - addition
      - multiplication
      - subtraction
      - division
      - EqualTo
      - Exponent
      - GCD
      - GreaterThan
      - LCM
      - LessThan
      - Modulus
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
networks:
  sample: